backend:
  name: github
  repo: Tanka2610/fedulina-works
  branch: main
  auth_type: pkce

media_folder: images/portfolio
public_folder: /images/portfolio

collections:
  - name: albums
    label: Альбомы
    folder: data
    create: true
    fields:
      - name: title
        label: Название
        widget: string
      - name: category
        label: Категория
        widget: select
        options:
          - wedding
          - portrait
          - studio
      - name: cover
        label: Обложка
        widget: image
      - name: photos
        label: Фото
        widget: list
        field:
          name: url
          label: Фото
          widget: image